#include<iostream>
using namespace std;
main(){
	int Number_1;
	int Number_2;
	int Number_3;
	int Number_4;
	int Number_5;
	int Number_6;
	int Number_7;
	int Number_8;
	int Number_9;
	int Number_10;
	int Number_11;
	int Number_12;
	int Number_13;
	int Number_14;
	int Number_15;
	cout<<"Number 1: ";
	cin>>Number_1; 
	cout<<"Number 2: ";
	cin>>Number_2;
	cout<<"Number 3: ";
	cin>>Number_3;
	cout<<"Number 4: ";
	cin>>Number_4;
	cout<<"Number 5: ";
	cin>>Number_5;
	cout<<"Number 6: ";
	cin>>Number_6;
	cout<<"Number 7: ";
	cin>>Number_7;
	cout<<"Number 8: ";
	cin>>Number_8;
	cout<<"Number 9: ";
	cin>>Number_9;
	cout<<"Number 10: ";
	cin>>Number_10;
	cout<<"Number 11: ";
	cin>>Number_11;
	cout<<"Number 12: ";
	cin>>Number_12;
	cout<<"Number 13: ";
	cin>>Number_13;
	cout<<"Number 14: ";
	cin>>Number_14;
	cout<<"Number 15: ";
	cin>>Number_15;
	int sum_of_first_five;
	sum_of_first_five=Number_1+Number_2+Number_3+Number_4+Number_5;
	int multiply_second_five;
	multiply_second_five=Number_6*Number_7*Number_8*Number_9*Number_10;
	int subtract_last_five;
	subtract_last_five=Number_11-Number_12-Number_13-Number_14-Number_15;
	int final_result;
	final_result=(sum_of_first_five)+(multiply_second_five)-(subtract_last_five);
	cout<<"The final result is: "<<final_result;	
}